#!/usr/bin/python

import pymongo
import time

import genesis
import unit.create
import unit.update
import unit.destroy

execution_instance = str(int(time.time()))

mongo_host = 'localhost'
mongo_port = 27017

mongo_db = 'population'
mongo_collection_births = 'births_' + execution_instance
mongo_collection_deaths = 'deaths_' + execution_instance
mongo_collection_matches = 'matches_' + execution_instance

init_pop_count = 200		# population count to generate in genesis


def _mongo_connect(host, port):
	try:
		mongo_client = pymongo.MongoClient(host, port)
		print("Connected to " + mongo_host + " on port " + str(mongo_port))
		return(mongo_client)

	except:
		mongo_client = 'FALSE'
		raise SystemExit("An error occured connecting to the MongoDB Server")

def _genesis(collection_births, collection_matches, count):
	genesis.StartPopulation(collection_births, collection_matches, count)


def _population(collection_births, collection_deaths, collection_matches):
	iteration = 0
	while 1:
	        iteration += 1
	        # Create Units
	        unit.create.Create(collection_births, collection_matches, iteration)
	
	        # Update Units
	        unit.update.Update(collection_births, collection_matches, iteration)
	
	        # Destroy Units 
	        unit.destroy.Destroy(collection_births, collection_deaths, iteration)

		pop_count = collection_births.count()
		print("the iteration is " + str(iteration) + " , the population count is " + str(pop_count))

		if (pop_count == 0):
			raise SystemExit("Your population is dead, it lasted for " + str(iteration) + " iterations.")

	        time.sleep(.1)
		



if __name__ == '__main__':
	client = _mongo_connect(mongo_host, mongo_port)

	# Connect to Mongo database and set collection using client connection
	db = client[mongo_db]
	collection_births = db[mongo_collection_births]
	collection_deaths = db[mongo_collection_deaths]
	collection_matches = db[mongo_collection_matches]

	
	# Run genesis - create population starting point
	_genesis(collection_births, collection_matches, init_pop_count)

	# Run population sim
	_population(collection_births, collection_deaths, collection_matches)
	
	





